### ISSUE TITLE
Bill of Materials (BoM) and Sources

### ISSUE THREAD

**Issue by zenny** [ttempe/YASK#1]
@ttempe 

Thanks for posting this. 

However, I wish you post a table of bill of materials (BoM) and the sources from where it can be ordered.

Some suggestions:
1. Btw, would it be not wonderful if you change the lower plate to a metal one or HDPE with a 3/4" knob at the center (similar to ectosteno or multisteno) to mount to a keyboard?
2. Can the board be a bit modded to look angled like BBSteno (https://mechwild.com/product/bb-steno/) for ergonomics?

Cheers and happy new year 2023.
/z

**Comment by ttempe** [comment]
You are right, you can choose a mix of materials. My PCB manufacturer usually has a MOQ of 5, so unless you wanted to make more than 2 keyboards, a 2nd PCB makes the whole keyboard much more sturdy for basically free.

Regarding the BOM, please refer to the my comment on the Youtube video for V1. I can't recommend any suppliers, as I live in PR China and do my shopping on Taobao, which is not directly accessible outside China.

V2 is more aggressively angled than BBSteno it seems. The BOM is the same, except for the keys.  

Have fun,
