### ISSUE TITLE
hard to find kailh choc switches. alternatives?

### ISSUE THREAD

**Issue by jappyjan** [ttempe/YASK#2]
Is it possible to use different kind of switches?
It seems to be really hard to buy kailh choc switches currently...

**Comment by ttempe** [comment]
Sorry, the Kailh Choc use a proprietary footprint, so if you want to used different switches on the YASK V2, you'll need to modify the PCB design. You can do so on OSW Hub directly.

The V1 uses standard Cherry-type switch sockets, so no problem there. The software will work with any brand of switch as well.
